### ISSUE TITLE
Visible only one element 

### ISSUE THREAD

**Issue by kubitre** [mwri/cytoscape-dom-node#1]
Hello @mwri . I used u lib, it's cool, but i have one problem. When i attached to cy elements more that one visible on grid only 1 element 
![image](https://user-images.githubusercontent.com/32496864/136659084-80e4752b-5a9a-4b25-9677-05a5953a517b.png)

**Comment by mwri** [comment]
@kubitre Did you solve your problem? I'm marking this invalid now, as there's no demonstration / reproducible problem, no way to know what the problem might be, but certainly it IS demonstrably possible to attach to multiple nodes, as illustrated by [codepen](https://codepen.io/mwri/pen/abWdVOG) so AFAIK it is a problem with your usage. It would be worthless really if it couldn't handle multiple nodes/elements... if you think there's a bug though, please consider posting more infor, and/or a demo.

**Comment by mwri** [comment]
@kubitre Closing this, as it is 5 months with no demonstration. By all means open it again if you believe it appropriate.
